Init Commit
HappyKod/gophkeeper pull request #1
Opened 2023-03-07 14:40 UTC by HappyKod

2023-03-12 22:15 UTC, tmvrus requested changes
Я не могу принять эту работу, поскольку нет клиента и не реализован механизм обновления секретов.

2023-03-12 22:15 UTC, tmvrus commented on internal/gophkeeperserver/api/handlers/register.go
> +		c.String(http.StatusInternalServerError, constans.ErrorUnmarshalBody)
это все же StatusBadRequest

2023-03-12 22:15 UTC, tmvrus commented on internal/gophkeeperserver/api/handlers/register.go
> +		c.AbortWithStatus(http.StatusBadRequest)
хорошо бы еще писать клиенту о том, что не так с запросом

2023-03-12 22:15 UTC, tmvrus commented on internal/keeperstorage/keeperpgstorage/pg-storage.go
> +		LIMIT 1
QueryRowContext подразумевает что в результаты будут только одна запись, по этой причине LIMIT 1 не имеет смысла

2023-03-12 22:15 UTC, tmvrus commented on internal/keeperstorage/keeperpgstorage/pg-storage.go
> +		set owner_id = $1 AND is_deleted = true
UPDATE так не работает
https://postgrespro.ru/docs/postgresql/15/sql-update?lang=ru-en
похоже этот код вообще не тестировался :(

2023-03-12 22:15 UTC, tmvrus commented on internal/keeperstorage/keeperpgstorage/pg-storage.go
> +		if err == sql.ErrNoRows {
правильней все же erros.Is(err, sql.ErrNoRows)

2023-03-12 22:15 UTC, tmvrus commented on internal/keeperstorage/keeperpgstorage/pg-storage.go
> +		secret_type TEXT NOT NULL,
выглядит так что secret_type никак не ограничен, хотя в ТЗ есть список

2023-03-14 14:43 UTC, HappyKod commented on internal/keeperstorage/keeperpgstorage/pg-storage.go
> +		LIMIT 1
Да вы правы

2023-03-16 12:08 UTC, tmvrus approved these changes
Работа хорошая, это пожалуй, лучшая реализации клиента на когорте. 
К сожалению, мне не удалось добиться синхронизации между клиентами:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/554425/225611398-b9d672d4-09d5-4e33-8a5c-c94a1ea76b9d.png">

2023-03-16 13:46 UTC, merged